# Dependabot configuration for automatic dependency updates
version: 2
updates:
  # Enable version updates for npm (functions directory)
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "ramiefathy"
    labels:
      - "dependencies"
      - "functions"
    commit-message:
      prefix: "deps(functions)"
      include: "scope"
    
  # Enable version updates for npm (web directory) 
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "ramiefathy"
    labels:
      - "dependencies"
      - "web"
    commit-message:
      prefix: "deps(web)"
      include: "scope"
      
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "ramiefathy"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
