name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Web deps
        working-directory: apps/PrecisionLearnDerm/web
        run: npm ci
      - name: Build Web
        working-directory: apps/PrecisionLearnDerm/web
        run: npm run build
      - name: Test Web
        working-directory: apps/PrecisionLearnDerm/web
        run: npm run test
      - name: Install Functions deps
        working-directory: apps/PrecisionLearnDerm/functions
        run: npm ci && npm run build
