name: Code Coverage

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  codecov:
    name: Upload Coverage
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'workflow_run' || 
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install web dependencies
        working-directory: web
        run: npm install --no-audit --no-fund
      
      - name: Run web/frontend tests with coverage
        working-directory: web
        run: npm run test:coverage
        env:
          CI: true
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./web
          files: |
            ./web/coverage/lcov.info,
            ./web/coverage/coverage-final.json,
            ./web/coverage/clover.xml
          fail_ci_if_error: true
          flags: frontend,web
          name: web-frontend-coverage
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Comment PR with coverage report
        if: github.event_name == 'pull_request'
        uses: codecov/codecov-action@v4
        with:
          directory: ./web
          files: |
            ./web/coverage/lcov.info,
            ./web/coverage/coverage-final.json
          flags: frontend,web
          name: web-frontend-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          comment: true
          comment_on: pr
          fail_ci_if_error: false
      
      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            web/coverage/
          retention-days: 30
      
      - name: Coverage Summary
        if: always()
        run: |
          echo "## Coverage Report Summary" >> $GITHUB_STEP_SUMMARY
          if [ -f "web/coverage/lcov-report/index.html" ]; then
            echo "Coverage reports generated successfully." >> $GITHUB_STEP_SUMMARY
            echo "Check the Codecov dashboard for detailed coverage analysis." >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ Coverage reports not found. Check test configuration." >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Setup Instructions for Maintainers" >> $GITHUB_STEP_SUMMARY
          echo "1. Visit https://codecov.io and sign in with GitHub" >> $GITHUB_STEP_SUMMARY
          echo "2. Add this repository to codecov" >> $GITHUB_STEP_SUMMARY
          echo "3. Add CODECOV_TOKEN in repository secrets if private" >> $GITHUB_STEP_SUMMARY
          echo "4. Ensure package.json has 'test:coverage' producing lcov" >> $GITHUB_STEP_SUMMARY
