name: Deploy to Firebase

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Firebase Functions and Hosting
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Install Functions Dependencies
        working-directory: functions
        run: |
          echo "Node version: $(node --version)"
          echo "npm version:  $(npm --version)"
          npm ci || npm install
          npm run build

      - name: Install Web App Dependencies
        working-directory: web
        run: |
          echo "Building web app..."
          echo "Node version: $(node --version)"
          echo "npm version:  $(npm --version)"
          npm install --no-audit --no-fund
          npm run build

      - name: Deploy Firebase Hosting and Functions
        run: |
          npm install -g firebase-tools@latest
          firebase deploy --only hosting,functions --project "${{ secrets.FIREBASE_PROJECT_ID }}" --non-interactive --force

      - name: Deployment succeeded
        if: success()
        run: echo "✅ Deployment successful!"

      - name: Deployment failed
        if: failure()
        run: echo "❌ Deployment failed. Check logs above."
