name: Deploy to Firebase

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Firebase Functions
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # Install functions dependencies
      - name: Install Functions Dependencies
        working-directory: ./functions
        run: |
          echo "Node version: $(node --version)"
          echo "npm version: $(npm --version)"
          # Remove problematic lockfile and reinstall fresh
          rm -f package-lock.json
          npm install
          npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          # Deploy functions with environment variables
          # Note: GEMINI_API_KEY should be set using Firebase Functions secrets
          # Run this command manually once: 
          # firebase functions:secrets:set GEMINI_API_KEY
          
          firebase deploy --only functions --token "${FIREBASE_TOKEN}" --non-interactive

      - name: Deployment Status
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed. Check logs above."
          fi
