name: Deploy to Firebase

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Firebase Functions and Hosting
    runs-on: ubuntu-latest
    environment: production
    env:
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json

      - name: Install Functions Dependencies
        working-directory: ./functions
        run: |
          echo "Node version: $(node --version)"
          echo "npm version: $(npm --version)"
          npm ci || npm install
          npm run build

      - name: Install Web App Dependencies
        working-directory: ./web
        run: |
          echo "Building web app..."
          echo "Node version: $(node --version)"
          echo "npm version: $(npm --version)"
          npm ci || npm install
          npm run build

      - name: Deploy Firebase Hosting and Functions
        run: |
          npm install -g firebase-tools@latest
          # Write service account JSON robustly (preserves newlines)
          printf '%s' "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > /tmp/service-account-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/service-account-key.json
          firebase deploy --only hosting,functions --project "${FIREBASE_PROJECT_ID}" --non-interactive
          rm /tmp/service-account-key.json

      - name: Deployment succeeded
        if: success()
        run: echo "✅ Deployment successful!"

      - name: Deployment failed
        if: failure()
        run: echo "❌ Deployment failed. Check logs above."
